### ISSUE TITLE
Example for /api/execution

### ISSUE THREAD

**Issue by Dommii** [infolis/infolis-web#10]
As a user, I would expect that an execution like 

``` json
{
  "algorithm": "io.github.infolis.algorithm.FrequencyBasedBootstrapping",
  "inputFiles": [
    "e6d33630-8d06-11e5-8a0d-770a3ae0f19d"
  ],
  "patterns": [
    "9ab57ad0-87a0-11e5-8579-295800119092"
  ]
}
```

works (also not sure what is wrong). Error message:

```
"stack": "SyntaxError: Unexpected token }\n  at Object.parse (native)\n  at parse (/home/infolis-web/infolis-web/node_modules/body-parser/lib/types/json.js:88:17)\n  at /home/infolis-web/infolis-web/node_modules/body-parser/lib/read.js:116:18\n  at invokeCallback (/home/infolis-web/infolis-web/node_modules/body-parser/node_modules/raw-body/index.js:262:16)\n  at done (/home/infolis-web/infolis-web/node_modules/body-parser/node_modules/raw-body/index.js:251:7)\n  at IncomingMessage.onEnd (/home/infolis-web/infolis-web/node_modules/body-parser/node_modules/raw-body/index.js:308:7)\n  at IncomingMessage.emit (events.js:104:17)\n  at _stream_readable.js:908:16\n  at process._tickCallback (node.js:355:11)\n",
  "message": "Unexpected token }",
  "body": "{\n  \"algorithm\": \"io.github.infolis.algorithm.FrequencyBasedBootstrapping\",\n  \"inputFiles\": [\n    \"e6d33630-8d06-11e5-8a0d-770a3ae0f19d\"\n  ],\n  \"patterns\": [\n    \"9ab57ad0-87a0-11e5-8579-295800119092\"\n  ],  \n}",
  "status": 400,
  "statusCode": 400
```

**Comment by Dommii** [comment]
Leaving out the last comma helps ;) but leads to another error:
"ValidationError: Path `status` is required."

**Comment by kba** [comment]
Posting

`curl -X POST --header "Content-Type: application/json" --header "Accept: application/json" -d "{
  \"algorithm\": \"io.github.infolis.algorithm.FrequencyBasedBootstrapping\",
  \"inputFiles\": [
    \"e6d33630-8d06-11e5-8a0d-770a3ae0f19d\"
  ],
  \"patterns\": [
    \"9ab57ad0-87a0-11e5-8579-295800119092\"
  ]
}" "http://infolis.gesis.org/infolink/api/execute"`

works for me. E.g. http://infolis.gesis.org/infolink/api/execution/a47b2940-8d16-11e5-bb74-fb61514d42aa

However, it is not valid to post this to `/infolink/api/execution` which is the endpoint that expects a new Execution object to persist to the datastore. The `/infolink/api/execute` is a non-RESTful helper to post a new execution and start it on the backend.
