### ISSUE TITLE
Data Model up-to-date

### ISSUE THREAD

**Issue by kba** [infolis/infolis-web#16]
@Dommii  @bolandka Please comment on whether https://github.com/infolis/infolis-web/blob/master/data/infolis.tson properly reflects the Java API.

**Comment by Dommii** [comment]
- dc:version on current date?
- what does rdf:seeAlso refer to?
- insert new comments? maybe also add seeAlso for the variables where we have @link in the code?
- does it make sense to have the default values in the data model?
- can we better indicate whether really a string of a URI is the type?
- Execution:
  *\* missing BibliographyExtractor in enum algorithm
  *\* missing: BootstrapStrategy, metaDataExtractionStrategy, linkedEntities, tags, overwriteTextFiles
- Entity: assosications? or do we not show them in the DM because they are just internally used?
- SearchResult: does not have a 'name' but a list of titles, does not  have a textRef
                        TODO: date is currently a string, should be a Date in the code (and then in the DM)
- InfolisPattern: msissing textRef, again associations etc.
- InfolisFile: does not have 'created'
- TextualReference: reference = term? if this is not the case, where is the term? pattern, mentionsReference is missing, file = textfile?

**Comment by zuphilip** [comment]
Are [these lines](https://github.com/infolis/infolis-web/blob/master/data/infolis.tson#L29):

```
@context
...
    rdfs:seeAlso
        @type @id
```

useful anyhow? I think this results in the blank node `_:b4` in the [online schema](http://infolis.gesis.org/infolink/schema) which is never the subject of anything.

**Comment by kba** [comment]
@zuphilip You're right, it doesn't at that point. Probably a fragment.

**Comment by kba** [comment]
> can we better indicate whether really a string of a URI is the type?

I have proper dbrefs (`hasOne` and `hasMany`) in a separate branch, which I hopefully will be able to roll out tomorrow.

**Comment by kba** [comment]
> Entity: assosications? or do we not show them in the DM because they are just internally used?

From what I remember, we agreed that those would not be persisted.

**Comment by Dommii** [comment]
Still open:
- insert new comments
- missing: metaDataExtractionStrategy, linkedEntities, tags, overwriteTextFiles
  -> how to describe these enums, see BootstrapStrategy as an example (does it make sense?)
- SearchResult: does not have a 'name' but a list of titles, does not have a textRef TODO: date is currently a string, should be a Date in the code (and then in the DM)
- InfolisPattern: msissing textRef, again associations etc.
- InfolisFile: does not have 'created'
- TextualReference: reference = term? if this is not the case, where is the term? pattern, mentionsReference is missing, file = textfile?

New questions: 
- sometimes it's just "type" sometimes "type:" -> should be consistent
- what does "index" mean?

**Comment by kba** [comment]
> what does "index" mean?

Whether MongoDB creates an index for that prop

> sometimes it's just "type" sometimes "type:" -> should be consistent

Yes, it should, but TSON is pretty lenient about delimiters/whitespace. Nonetheless, consistent is better I agree.

**Comment by kba** [comment]
> InfolisPattern: msissing textRef, again associations etc.

`associations` was non-persistent I think. `textualReference`, I am not sure, I think it's redundant. @bolandka ?

**Comment by kba** [comment]
> how to describe these enums, see BootstrapStrategy as an example (does it make sense?)

``` coffee
MyClass
  myPropWithEnumRange:
    @context:
      ...
    enum: [
      "value1"
      "value2"
      "..."
    ]
```

e.g. https://github.com/infolis/infolis-web/blob/d68e42df2426b94315e62944007ff00401827997/data/infolis.tson#L184

**Comment by kba** [comment]
> InfolisFile: does not have 'created'

Removed by https://github.com/infolis/infolis-web/commit/33a89ecc3a3d3eabeed9d1f10d4f5d2b6fcefdba

**Comment by kba** [comment]
> TextualReference: reference = term? if this is not the case, where is the term? pattern, mentionsReference is missing, file = textfile?

@Dommii  Please expand.

**Comment by Dommii** [comment]
I was confused whether the Variable 'reference' contains the term we searched for, e.g. 'ALLBUS' or something different. But as far as I see, this is the case.
Both pattern and mentionsReference are not going to be persisted so it's fine that they are not in the DM.
There is no variable with the name 'file' in the class TextualReference but the variable with the name 'textFile'.

**Comment by bolandka** [comment]
commented on the question about associations here: https://github.com/infolis/infolis-web/issues/30

**Comment by kba** [comment]
The data model has evolved quite a lot in the last weeks. Please open new issues for specific problems, so we can keep track of regressions and changes.
