### ISSUE TITLE
Syntax Highlighting is not working in Edge Browser

### ISSUE THREAD

**Issue by zuphilip** [infolis/infolis-web#17]
The error message shows something like `'InfolinkClient' is undefined` in searchQuery (1,492).

**Comment by zuphilip** [comment]
Syntax highlighing is also not working on my Samsung tablet here. Can someone confirm that?

**Comment by kba** [comment]
`'InfolinkClient' is undefined` is due to me working on the JS client. This is to be expected.

Nonetheless, it should work on phones, we need to test that.

**Comment by kba** [comment]
Works on Android for me

**Comment by zuphilip** [comment]
Okay, I tested again in it seems fine now on the Tablet and also in Edge browser on Win 10.
