### ISSUE TITLE
Textbox for intro and/or description on each main view

### ISSUE THREAD

**Issue by kaiec** [infolis/infolis-web#22]
When people arrive at the Linked Data Fragments View, the browse API or browse schema and the play view (i.e., every view that is directly reached via Menu or the direct links from the homepage), a box at the top of the view should be shown that contains a brief description. I deliver texts, but have no idea how the box is to be created,

**Comment by kba** [comment]
No need, I can integrate them. Just post the texts here or edit the `help` blocks in the jade files in `/views`.

**Comment by kba** [comment]
turned them off again for now because they are in the way while developing. Give me a ping when you have the texts and I'll turn them on again.

**Comment by kaiec** [comment]
Here are some texts, sorry for being last second:

***\* LDF Service

<p>You can query our data using [[http://linkeddatafragments.org/][Linked Data Fragments]]. This basically allows for filtering the statements based on combinations of subject, predicate and/or object. For instance, fill in a URI in the subject field and you get all statements about this subject.</p>

<p>
Note: This service ist not yet fully functionable. [[https://github.com/infolis/infolis-web/issues/67][Filtering by object]] is not yet implemented and we know that there are bugs in filtering by subject and predicate combinations. We would appreciate if you [[https://github.com/infolis/infolis-web/issues][create an issue]] with an example if you spot a problem. 
</p>

***\* Schema

<p>Our data schema not only addresses the actual [[http://infolis.gesis.org/infolink/schema/EntityLink][links]] between publications and research data, but also contains the process model to obtain these links by [[http://infolis.gesis.org/infolink/schema/Execution][executing]] [[http://infolis.gesis.org/infolink/schema/algorithm][algorithms]] by means of our services. A higher-level description of the schema is provided [[http://infolis.github.io/data-model/][here]].
</p>

***\* API

<p>
Feel free to look around and test our API. Basically, there are only two essential methods for uploading files and executing a linking algorithm. Note that uploaded files will not be available for download for copyright reasons. 
</p>

<p>
During the execution of the algorithm, many additional resources are created to reflect the status of the execution and the provenance chain for the produced links. To create these resources and get access to them afterwards, we provide many additional methods that you probably do not need to know about at the beginning.
</p>

<p>
Note: This API is under heavy development and far from stable. If you have problems using it or find a bug, please [[https://github.com/infolis/infoLink/issues][create an issue]].
</p>

**Comment by kba** [comment]
not markdown.

**Comment by kba** [comment]
Still missing: http://infolis.gesis.org/infolink/api/stats

**Comment by kba** [comment]
http://infolis.gesis.org/infolink/play/demo1

**Comment by kba** [comment]
@infolis/all Propopsed workflow for UI documentation / help texts:
- Fork infolis/infolis-web
- Create a topical branch
- Create a [Github Flavored Markdown](https://guides.github.com/features/mastering-markdown/) file under `/help`
- Open a pull request so we can discuss wording and I'll integrate it.

**Comment by bolandka** [comment]
created a help text for /play/demo1 following the proposed workflow. Comments welcome! (Please comment the pull request directly).

**Comment by bolandka** [comment]
added some comments on the help text for /api here: https://github.com/infolis/infolis-web/commit/0793084bdd2fe40d9d9c3b85b3e7b021915184b3

**Comment by bolandka** [comment]
thought it might be nice to have more detailed explanations on the api help page. I added a suggestion here: https://github.com/infolis/infolis-web/pull/79

**Comment by bolandka** [comment]
created a help text for /api/stats here: https://github.com/infolis/infolis-web/pull/80

**Comment by kba** [comment]
We have help for all publicly available features of the web UI now.
