### ISSUE TITLE
Duplicates in the swagger api

### ISSUE THREAD

**Issue by zuphilip** [infolis/infolis-web#23]
All restful API endpoints appear twice: once in the large and confusing list and once in the smaller list. I suggest to delete `rest-ld-all`.

**Comment by kba** [comment]
The non-generated endpoints should be open by default.

When the class-based sections are all open, it's a bit hard to navigate, then it is easier to use the large list. 

I just haven't had the time to write the jQuery-foo to do that.
- Open the `helpers` (rename!) by default
- Close the `rest-ld-*` by default

**Comment by zuphilip** [comment]
1. I agree on open and close the sections.
2. However, I would still suggest to hide/delete the `rest-ld-all`, because that is otherwise misleading (i.e. all  but there are others).
3. A nice-to-have would also be a label "Show/Hide" on the right of closed section similar to the [demo example](http://petstore.swagger.io/#/).

**Comment by kba** [comment]
> A nice-to-have would also be a label "Show/Hide" on the right of closed section similar to the demo example.

That I found even more confusing, that's why I removed it. Can put it back in though.

**Comment by zuphilip** [comment]
Thank you. In 3. I actually just meant the _one_ option Show/Hide. The other two options are either the almost the same or not really usefull. However, we can IMO leave it as it is for the moment.
