### ISSUE TITLE
BibliographyExtraction call has not been tested

### ISSUE THREAD

**Issue by bolandka** [infolis/infolis-web#24]
example call: https://github.com/infolis/infolis-web/wiki/API-calls-to-algorithms

**Comment by bolandka** [comment]
part of https://github.com/infolis/infolis-web/issues/20

needs a text file uri to work (and an actual text file being referenced by the uri), is one available on the server? The uris I tried all led to FileNotFoundExceptions (e.g. java.io.FileNotFoundException: File '4493.txt' does not exist)

**Comment by zuphilip** [comment]
Try to choose one here: http://infolis.gesis.org/infolink/api/infolisFile

**Comment by bolandka** [comment]
I did, those are the ones that threw the error.

**Comment by zuphilip** [comment]
I don't think that the files are a problem here. Could there be a problem with the algorithm or how the data is transported through backend, frontend? @kba Any suggestion?

**Comment by bolandka** [comment]
I'll check whether it works locally [Update: it does, as expected]

**Comment by kba** [comment]
`4493.txt` sound suspicious. Are we using a LocalFileResolver on the server?

**Comment by bolandka** [comment]
The same uri works in a FrequencyBasedBootstrapping call

**Comment by kba** [comment]
This was a bug in the file resolving, https://github.com/infolis/infoLink/commit/fd26224c1efe23767babe109fc80b8314bb29461 fixed it

**Comment by bolandka** [comment]
Thank you. I updated the example call and it now works fine.
