### ISSUE TITLE
How to specify tags for algorithms, both search and assignment

### ISSUE THREAD

**Issue by bolandka** [infolis/infolis-web#25]
comments on how to ideally specify the tags in the json calls are welcome, I can adapt the code accordingly

**Comment by kba** [comment]
Don't we already have a `tags` field in the execution?

**Comment by bolandka** [comment]
yes, we do, but that did not seem to be sufficient. Example: Suppose you want to choose all documents having the tag "ssoar" and apply all patterns having the tag "some_subset_of_ssoar" on them. Problem: how to specify which tags to use for which purpose if the execution has only one set? 

I now implemented it according to the example: json objects are now supported for tags, like this: 

``` js
"tags": {
   "InfolisPattern": ["tag1", "tag2"],
   "InfolisFile": ["tag2", "tag3"] 
} 
```

(here: https://github.com/infolis/infoLink/tree/support_tags)
If the key translates to the InfolisPattern class, its tag set is used to set uris for setPatternUris(). If it translates to the InfolisFile class, its tag set is used to set uris for setInputFiles(). If it translates to Entity or something else: I actually don't know in which cases that could be useful, so it doesn't do anything right now ;) But including additional cases should be straight-forward.

Execution still has its old tags field: that set of tags describes the Execution in case we'd like to identify it with them. The actual tags for selecting files, patterns or other things are now stored in the additional field tagMap. <- should probably rename it to something more self-explanatory like selectionTags or something like that.

**Comment by kba** [comment]
The approach is sound and I can see why just `tags` isn't enough. It's just a matter of organizing the code in a way to avoid any map-like structures. Converting the `Multimap<String,String>` to a Java class and representing it in our data model will make serialisation easier and conformant with RDF limitations.

I'd then argue for making it clear in the documentation and our code that `Execution.tags` is for _assigning_ tags to some resource or resources and `Execution.tagMap` for selecting resources _by their tag_.

**Comment by bolandka** [comment]
Good point, thanks. Done. 
Yes, we absolutely have to make that clear!

**Comment by bolandka** [comment]
entered the wrong issue in my commit message, sry -.- didn't notice it was in a different location. Anyway, it's fixed in https://github.com/infolis/infoLink/commit/830b7278b57403a1ae30a926206c93eb4e25508c

**Comment by bolandka** [comment]
opened a new issue about the documentation at https://github.com/infolis/infolis-web/issues/31. 

This issue remains open until the json command has been successfully tested.

**Comment by bolandka** [comment]
works, see https://github.com/infolis/infolis-web/issues/20#
