### ISSUE TITLE
How to call the non-REST methods?

### ISSUE THREAD

**Issue by kba** [infolis/infolis-web#26]
Right now they are called **helpers** with the silly description `helper : Helpers. RESTful they ain't but useful they ain'tn't.`.

What would be a good name for that group? Description?
- Popular
- Simple API

I'm open for suggestions.

**Comment by zuphilip** [comment]
main-actions?

**Comment by bolandka** [comment]
Essential API? To express that these methods both represent the main actions as zuphilip suggested and also are the most simple and popular ones as kba suggested.

**Comment by kba** [comment]
I like essential. Committed a proposal.

**Comment by zuphilip** [comment]
:+1:

**Comment by bolandka** [comment]
essential and advanced should make it clear, like it the way you proposed :+1:

**Comment by kba** [comment]
ok then, let's close another one.
