### ISSUE TITLE
Error in groups of Swagger API 

### ISSUE THREAD

**Issue by zuphilip** [infolis/infolis-web#29]
There is a second `post /api/upload` under the group `rest-ld-infolisFile` which is not necessary (and I guess not RESTful):

![api-error](https://cloud.githubusercontent.com/assets/5199995/11270485/c0507eb8-8ebf-11e5-973a-ac57c895879b.jpg)

**Comment by kba** [comment]
Yes, that was on purpose, but now it's inconsistent. Will change.
