### ISSUE TITLE
Spaces in the header

### ISSUE THREAD

**Issue by zuphilip** [infolis/infolis-web#3]
I suggest to include some spaces in the header (menue line) from left and right, e.g. one unit in the bootstrap 12-grid. That is AFAIK kind of similar to what Twitter is doing. See:

![header-menu-with-spaces](https://cloud.githubusercontent.com/assets/5199995/11197017/dd9921e8-8cba-11e5-8265-21539e6fb010.jpg)

I don't know where and how to change that here...

**Comment by kba** [comment]
Header is defined over here: https://github.com/infolis/infolis-web/blob/master/views/header.jade

CSS is here: https://github.com/infolis/infolis.github.io/blob/master/css/style.css Feel free to add to that but keep responsiveness in mind (zoom in&out and make sure nothing breaks for small screens)
