### ISSUE TITLE
Document and explain Execution.tags and Execution.tagSet

### ISSUE THREAD

**Issue by bolandka** [infolis/infolis-web#31]
see https://github.com/infolis/infolis-web/issues/25

**Comment by kba** [comment]
Best to add descriptions to https://github.com/infolis/infolis-web/blob/master/data/infolis.tson. Then we can show them in Swagger etc.

**Comment by kba** [comment]
In addition to https://github.com/infolis/infolis-web/wiki/API-calls-to-algorithms of course

**Comment by bolandka** [comment]
I added explanations to both, please have a look and close this issue if you are ok with the explanations.
