### ISSUE TITLE
Data Model: Execution.tags and InfolisPattern.textualReferences are missing

### ISSUE THREAD

**Issue by bolandka** [infolis/infolis-web#34]
https://github.com/infolis/infolis-web/issues/28

Execution.tags
InfolisPattern.textualReferences

and maybe others are missing

**Comment by kba** [comment]
Wasn't InfolisPattern.textualReferences supposed to be non-persistent @bolandka @Dommii

**Comment by bolandka** [comment]
yes you're right, sorry. It was the other direction that should be persisted
