### ISSUE TITLE
Error in /api/execute: Status 400, CastError

### ISSUE THREAD

**Issue by bolandka** [infolis/infolis-web#41]
Error: CastError: Cast to string failed for value \\"[object Object]\\" at path \\"tagMap\\"\n  at /home/infolis-web/mongoose-jsonld/src/handlers/restful.coffee:133:21

to reproduce, post for example the text extraction example at https://github.com/infolis/infolis-web/wiki/API-calls-to-algorithms

**Comment by kba** [comment]
Caused by https://github.com/infolis/infoLink/issues/39, should be fixed by https://github.com/infolis/infoLink/pull/41
