### ISSUE TITLE
Example Call demonstrating selection by tags is not up-to-date

### ISSUE THREAD

**Issue by bolandka** [infolis/infolis-web#43]
part of https://github.com/infolis/infolis-web/issues/20

**Comment by zuphilip** [comment]
The example and documentation are updated. Do we need also another `infolisEntityTags` for entities?

**Comment by kba** [comment]
> The example and documentation are updated. Do we need also another infolisEntityTags for entities?

Yes. So it cannot hurt to document it now and change the API and docs for all types of taggable things later in one go.

**Comment by bolandka** [comment]
sry edited the page while you wrote that, putting it back in

**Comment by zuphilip** [comment]
@kba Are the `infolisEntityTags` ready now? I didn't find it in the schema: http://infolis.gesis.org/infolink/schema/infolisEntityTags but the others are there e.g. http://infolis.gesis.org/infolink/schema/infolisFileTags

**Comment by kba** [comment]
@zuphilip They are not because it's not quite sure how they should be resolved for me. `infolisFileTags` resolves the tags to `Execution.inputFiles`, `infolisPatternTags` resolves the tags to `Execution.patterns` but what property of the Execution would `infolisEntityTags` (or `entityTags`) be resolved to right now? @bolandka @Dommii

**Comment by bolandka** [comment]
@kba I had the same question when writing the TagResolver. I can't think of a useful use-case for specifying entites via tags. Cause there's nothing to be done with them inside of an Excecution, they are rather products of an Execution and used to identify source files in EntityLinks. I would suggest to remove infolisEntityTags from the documentation and not implement them.

**Comment by bolandka** [comment]
We could support searching TextualReferences by tags though. Users could request to resolve TextualReferences of some tag to EntityLinks. I don't think this feature would be too useful, though, in practice because everything that could be achieved by such a call can already be achieved by posting requests with the existing features. But it would make sense, at least.
Therefore: maybe we can think about adding this later, wouldn't implement it right now :)

**Comment by kba** [comment]
What about EntityLinks?
