### ISSUE TITLE
schema/Algorithm fails with 404

### ISSUE THREAD

**Issue by zuphilip** [infolis/infolis-web#47]
http://infolis.gesis.org/infolink/schema/Algorithm

**Comment by kba** [comment]
Algorithm is not part of the data model. Is it linked somewhere?

**Comment by zuphilip** [comment]
https://github.com/infolis/infolis-web/wiki/API-calls-to-algorithms , first paragraph

**Comment by zuphilip** [comment]
And all occurences of `Algorithm` here http://infolis.gesis.org/infolink/schema

**Comment by kba** [comment]
> https://github.com/infolis/infolis-web/wiki/API-calls-to-algorithms , first paragraph

That was a typo, should be `algorithm`, not `Algorithm`. It worked before because of #28 and stopped working because of https://github.com/infolis/infolis-web/commit/aa59f3c62c8b5bbea29890632f3a3bdd52e8f673. I corrected the link.
