### ISSUE TITLE
[api/stats] Duplicate indexed fields

### ISSUE THREAD

**Issue by zuphilip** [infolis/infolis-web#51]
In http://infolis.gesis.org/infolink/api/stats some indexed fields are duplicated:
- SearchResult
  - name
- InfolisPattern
  -  luceneQuery
- InfolisFile
  -  md5 (occurs even 3 times)
- QueryService
  -  reliability
- EntityLink
  - confidence

**Comment by kba** [comment]
The list is more of an indicator which fields are indexed at all. I simplified the quite elaborate indexing scheme used by Mongo to only the fields, not their order in particular compound indexes.

That being said, I'll fix it.
