### ISSUE TITLE
ApplyPatternAndResolve sets FINISHED but does not seem to do anything

### ISSUE THREAD

**Issue by bolandka** [infolis/infolis-web#53]
https://github.com/infolis/infolis-web/issues/20

e.g. http://infolis.gesis.org/infolink/api/execution/57a7ffb0-8ff7-11e5-9b5a-a7305ed175fc

to reproduce, try the example call:
https://github.com/infolis/infolis-web/wiki/API-calls-to-algorithms#applypatternandresolve

...also does not log anything

**Comment by bolandka** [comment]
Update: patterns parameter in the example call points to invalid InfolisPattern (invalid in the way that a pattern like this should never be posted by the algorithm, see https://github.com/infolis/infolis-web/issues/61). Updating the example page...

With a correct InfolisPattern (e.g. "http://infolis.gesis.org/infolink/api/infolisPattern/ebc25f00-910b-11e5-93cc-8fd4c6a22003"), it throws a NullPointerException:

```
ERROR [pool-2-thread-2] i.g.i.d.CentralClient [CentralClient.java:145] URI must be absolute, io.github.infolis.resolve.DaraHTMLQueryService is NOT.
```

To reproduce, call

```
{
  "algorithm": "io.github.infolis.algorithm.ApplyPatternAndResolve",
  "inputFiles": [
    "http://infolis.gesis.org/infolink/api/infolisFile/b6453b30-90bc-11e5-a0e4-eb7dca62b932"
  ],
  "patterns": [
    "http://infolis.gesis.org/infolink/api/infolisPattern/ebc25f00-910b-11e5-93cc-8fd4c6a22003"
  ],
  "queryServices": ["io.github.infolis.resolve.DaraHTMLQueryService"]
}
```

**Comment by bolandka** [comment]
seems to be related to https://github.com/infolis/infoLink/issues/53: Query Services not posted

**Comment by Dommii** [comment]
Instead of "queryServices" "queryServiceClasses" must be used if the name of the query service and not a QueryService URI is used.

**Comment by bolandka** [comment]
Ah, the example call is wrong indeed, thanks!

Correcting this. But there's a NPE nevertheless:
http://infolis.gesis.org/infolink/api/execution/bbc0b670-9148-11e5-8932-2965e57e493a

That's probably already solved by the fix you commited, referencing the wrong issue https://github.com/infolis/infoLink/issues/53

So lets redeploy and test

**Comment by Dommii** [comment]
Yep, that's the one with the Entity of the TextualReference I currently fixed, but I think the DM is not reloaded yet.

**Comment by kba** [comment]
Shaky internet for me, will merge asap.

**Comment by Dommii** [comment]
Now it works :)! http://infolis.gesis.org/infolink/api/execution/740d9800-914f-11e5-b6a5-7ff80ae297d2
