### ISSUE TITLE
Tags: support AND / OR / NOT operations when searching for tags

### ISSUE THREAD

**Issue by bolandka** [infolis/infolis-web#58]
very useful e.g. when there are labels for languages + labels for scientific domains + labels for repositories etc.

**Comment by zuphilip** [comment]
I tried out the obvious, i.e. to specified `tags` multiple times, e.g. http://infolis.gesis.org/infolink/api/infolisFile?q=tags%3Afirst,tags%3Azuphilip . But the result will then ignore the first value completely and just output the same as http://infolis.gesis.org/infolink/api/infolisFile?q=tags%3Azuphilip .

**Comment by kba** [comment]
Yeah, the query tranlation from kv-pair to actual query is kinda dumb right now.

**Comment by kba** [comment]
OR works now for a single field e.g. http://infolis.gesis.org/infolink/api/infolisFile?q=tags%3Afirst,tags%3Azuphilip

The whole query is AND, though.

**Comment by kba** [comment]
It's all AND because we hardly need OR and it's easy to simulate with multiple AND queries
