### ISSUE TITLE
Graphical overview of the data model

### ISSUE THREAD

**Issue by Dommii** [infolis/infolis-web#6]
Should we add an overview picture about our data schema? I think the GraphViz functionality is very nice but especially for the schema not really easy to read ;).

**Comment by kba** [comment]
:+1:

**Comment by kba** [comment]
I created a page that contains the image here: http://infolis.github.io/data-model/

Feel free to edit the markdown page at https://github.com/infolis/infolis.github.io/blob/master/pages/data-model.md
