### ISSUE TITLE
404 Not found: Learn -> Data Model 

### ISSUE THREAD

**Issue by zuphilip** [infolis/infolis-web#62]
http://infolis.gesis.org/infolink/work/data-model

**Comment by kba** [comment]
The link in the header should be fixed. Though I'm not sure it is that helpful without any explanation. Maybe integrate it into the help for the [Data Model Explorer](http://infolis.gesis.org/infolink/play/data-model-explorer)?

**Comment by zuphilip** [comment]
Okay. IMO it is currently find under `Play`.
