### ISSUE TITLE
Umlauts

### ISSUE THREAD

**Issue by Dommii** [infolis/infolis-web#65]
Umlauts are not displayed correctly:
http://infolis.gesis.org/infolink/api/textualReference/74b597d0-914f-11e5-b6a5-7ff80ae297d2
As far as I tested it, the PDF Extraction can deal with Umlauts.

**Comment by bolandka** [comment]
seems we checked the same thing at the same time :D  https://github.com/infolis/infolis-web/issues/64

**Comment by kba** [comment]
:) Let's track it #64
