### ISSUE TITLE
Datasetify demo: Error uploading pdfs

### ISSUE THREAD

**Issue by bolandka** [infolis/infolis-web#66]
Tried to upload a corpus of 260 pdfs. Is a larger size of documents a problem for some reason? Uploading 28 documents at a time worked fine.

**Comment by zuphilip** [comment]
What was the error message or what happend exactly when trying to upload the 260 pdfs?

**Comment by kba** [comment]
I suppose it could crash the client  because it's uploading all 260 at the same time. Will have to limit that.

**Comment by bolandka** [comment]
"Upload failed" was the error message and then all single progress bars turn red. Would love to provide more info but that's all it displays (@kba: if you give me a hint where the upload process is logged, I can look into that in more detail. ) However, I think it's like @kba said: the pdfs are all processed in parallel and you can see more and more pdfs being processed while the ones before haven't finished (and won't, when new ones are added, they seem to wait for them to finish). Eventually, almost every pdf has a progress bar standing somewhere before 100% while the new one keep getting added and then it crashes (nicely, btw ;) ) 
Tried with 126 now, still not good. Trying to find a good number to limit it to.
70: still too much.

**Comment by bolandka** [comment]
Is there any timeout mechanism when uploading? Just tried with 50: watched to bars race to the destination, one by one, the last ones were almost there (some at the top still waiting for the last ones some meters before the finish) I was cheering them on: comeone, you're almost there! Just a few more steps! And then, suddenly: upload failed. It was like it was lurking in some corner just to jump at the poor pdfs so close to the finish. And the last 2 ones even continued being processed but then they were caught and their bars violently turned from green to red some seconds after the error message, even the one that just made it to 100% (and all others of course turned, too, before that).

**Comment by kba** [comment]
@bolandka Now you made me sad. I killed your files.

Anyway, simultaneous uploads are limited now. But that wasn't the problem. The problem was that I had missed a path segment in the client instantiation. Why the script waited until all files were finished to tell you, I cannot say. Malice, probably.
