### ISSUE TITLE
Linked Data Fragments query for objects

### ISSUE THREAD

**Issue by Dommii** [infolis/infolis-web#67]
When I try to query for an object, e.g. "http://infolis.gesis.org/infolink/schema/Execution", I get the following application error:
Cannot read property 'call' of undefined

**Comment by kba** [comment]
yep, no queries for objects for now.

**Comment by kba** [comment]
It would not be hard, we have this implemented for the simple search `q=property:id` but I do not see the merit of a Linked Data query engine for any envisioned use case at this moment.
