### ISSUE TITLE
Data Model Explorer rdfs:range missing

### ISSUE THREAD

**Issue by Dommii** [infolis/infolis-web#68]
The rdfs:range is not always displayed although it is included in the DM. For example, the property "reliability" of "QueryService" has "Number" as type but nothing is displayed in the DM explorer.
Not sure if this only holds for the numeric range.

**Comment by kba** [comment]
Fixed. BTW you can directly link to all elements in the DM explorer.

E.g. http://infolis.gesis.org/infolink/play/data-model-explorer#reliability/context

or

http://infolis.gesis.org/infolink/play/data-model-explorer#QueryService/props

Everything with that permalink button.
