### ISSUE TITLE
infolis.gesis.org seems COMPLETELY DOWN

### ISSUE THREAD

**Issue by zuphilip** [infolis/infolis-web#70]
E.g. not loading:

http://infolis.gesis.org/infolink/api
http://infolis.gesis.org/infolink/play/data-model-explorer

Moreover, the menu is not present.

**Comment by zuphilip** [comment]
Puh... It seems to work again.

**Comment by zuphilip** [comment]
Again down? @kba

**Comment by zuphilip** [comment]
Hm.. again down? @kba

**Comment by kba** [comment]
Reproducible hang on `/api/execution`, #71
