### ISSUE TITLE
Hangs on /api/execution

### ISSUE THREAD

**Issue by kba** [infolis/infolis-web#71]
`/api/execution` hangs.

**Comment by kba** [comment]
We currently have 30,000 executions, returning all of them on the collection REST GET call is unscalable. For now I've set a hard limit to 500 so it won't hang anymore but need to investigate a good strategy here.

**Comment by zuphilip** [comment]
I see also there is one executation under `started`: http://infolis.gesis.org/infolink/api/monitor#executions-STARTED and actually it was started 3 days ago. Is there maybe a connection to these down times?

**Comment by kba** [comment]
All the executions serialized as JSON amount to about 60 MB of raw data per request, which isn't necessarily streamed. That is what caused the hangs. If the frontend is unavailable, the backend can't update an execution, hence the started execution.

**Comment by kba** [comment]
Closing this and track progress on a proper fix in #74.
