### ISSUE TITLE
Closing help easier

### ISSUE THREAD

**Issue by zuphilip** [infolis/infolis-web#78]
After clicking on the question mark the corresponding help text is appearing. I feel that it should be easier to close this help text again. For example clicking anywhere in the "background" should close the help window. Is this possible to do?

**Comment by kba** [comment]
I had it setup to close on pressing `<Esc>` or toggle using `h` but all of those had side effects, interfering with Swagger and such. Will need to test this thoroughly.

**Comment by kba** [comment]
Now, pressing `<Esc>` should work again.
