### ISSUE TITLE
How does the filtering with the k-v pairs work?

### ISSUE THREAD

**Issue by Dommii** [infolis/infolis-web#8]
If I want to retrieve a specific InfolisFile, e.g. if I only have the id, how do I need to fill the value?

**Comment by Dommii** [comment]
Use /api/infolisFile/{id} ;)

**Comment by zuphilip** [comment]
Did you find out how to enter the key-value-pairs? I tried in `api/execution` the `q`-value `"algorithm: io.github.infolis.algorithm.TextExtractor"` i.e.

```
curl -X GET --header "Accept: application/json" "http://infolis.gesis.org/infolink/api/execution?q=%22algorithm%3A%20io.github.infolis.algorithm.TextExtractor%22"
```

but that does not work :(

**Comment by kba** [comment]
https://github.com/infolis/infolis-web/issues/8#issuecomment-157763629

Indeed, this needs work, was blocked by https://github.com/infolis/infoLink/tree/support_tags Will work on that once it's merged

**Comment by zuphilip** [comment]
Let me know if this should work, then I can test it.

**Comment by kba** [comment]
Documents in the collection can be filtered by the value of their fields.

The `?q=` parameter allows one to specify those field-value-pairs. The field-value pairs are separated by `,` (comma), field and value are separated by `:` (colon).

Example: To get an [InfolisFile](http://infolis.gesis.org/infolink/schema/InfolisFile) with a tag `zuphilip`:

> http://infolis.gesis.org/infolink/api/infolisFile?q=tags%3Azuphilip

**Comment by zuphilip** [comment]
Ah, now I understand how to input that in the swagger interface: without any quotation marks. E.g.

![k-v-parameters](https://cloud.githubusercontent.com/assets/5199995/11318344/0ea2d850-904f-11e5-85d9-92d867659c53.jpg)

This filtering seems for me quite powerful! Maybe we can clarify the description there better. I suggest to delete the quotation marks and maybe write

```
k-v-pairs to filter for: key1:value1,key2:value2
```

**Comment by zuphilip** [comment]
Thank you. I wrote some examples and documentation in https://github.com/infolis/infolis-web/wiki/Filtering-in-API-calls (might not yet be perfect). I guess we can then close this issue?

**Comment by kba** [comment]
Closing, we can discuss improvements in https://github.com/infolis/infolis-web/issues/58.
