### ISSUE TITLE
/api/stats contains indexed field "term" for TextualReference

### ISSUE THREAD

**Issue by bolandka** [infolis/infolis-web#81]
...which is linked to http://infolis.gesis.org/infolink/schema/term which does not exist (and should not exist).

Another link producing a 404 error: http://infolis.gesis.org/infolink/schema/created for field "created" in InfolisFile.

**Comment by kba** [comment]
These indexes were created before the data model changed. They are not in use anymore but that should not impact any queries that do not use them. I agree, we should re-index our datastore but this isn't a bug in that it should cause no problems.

**Comment by kba** [comment]
Most data dropped, InfolisFile reindexes, index stats should be fixed.
