### ISSUE TITLE
algorithms don't output created resources

### ISSUE THREAD

**Issue by bolandka** [infolis/infolis-web#89]
see https://github.com/infolis/infolis-web/issues/85

**Comment by kba** [comment]
This, too, should be fixed.

**Comment by bolandka** [comment]
The created resources are mentioned in the log but are not shown as a field of the execution, e.g. http://infolis.gesis.org/infolink/api/execution/fae40fc0-320e-11e6-a79d-fd4261354fe5. Obviously, a link was created but should this not be shown in the execution's _links_ field?

**Comment by kba** [comment]
Ah, right, it's that bug in the LD layer, I'm working on that. The data is stored though.

**Comment by kba** [comment]
I think this is not up-to-date anymore @bolandka

**Comment by bolandka** [comment]
yes, it's fixed. Thank you!
