### ISSUE TITLE
Exception in FrequencyBasedBootstrapping -> TokenizerStandford

### ISSUE THREAD

**Issue by bolandka** [infolis/infolis-web#90]
java.lang.NoSuchMethodError: edu.stanford.nlp.process.DocumentPreprocessor.setTokenizerFactory(Ledu/stanford/nlp/process/TokenizerFactory;)V
  at io.github.infolis.algorithm.TokenizerStanford.applyPTBTokenizer(TokenizerStanford.java:59)

to reproduce, use example call in wiki
(see https://github.com/infolis/infolis-web/issues/85)

**Comment by kba** [comment]
This was a bug in the build dependencies for infolis/infoLink. I think this is fixed now.
