### ISSUE TITLE
display "leftText" and "rightText" of TextualReference in addition to "reference"

### ISSUE THREAD

**Issue by bolandka** [infolis/infolis-web#96]
This would make it a lot easier to make sense of the generated data and validate it.
For example, when there's a reference "Bildungs" and it is linked to "Begleitstudie zur Umsetzung der "Bildungs- und Erziehungsempfehlungen für Kindertagesstätten in Rheinland-Pfalz", it is impossible to assess the validity of this link without further information on the context of the reference. Having the whole TextualReference helps in many of those cases.

**Comment by kba** [comment]
`leftText` and `rightText` are not persisted in the data model at the moment. I replaced `leftContext`/`rightContext` with it and test now.
